### ISSUE TITLE
Missing documentation on how (Python) coverage is captured

### ISSUE THREAD

**Issue by peterjc** [codecov/example-python#12]
I'm not sure if I should file this here, or over at https://github.com/codecov/codecov-python/issues

Following the minimal example documentation in https://github.com/codecov/example-python/blob/master/README.md and on https://codecov.io/guide I just tried adding the coverage bits to my ``.travis.yml`` and pushed to GtiHub, which triggered a TravisCI build. I got this at the end of the TravisCI log:

```
$ codecov
      _____          _
     / ____|        | |
    | |     ___   __| | ___  ___ _____   __
    | |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
    | |___| (_) | (_| |  __/ (_| (_) \ V /
     \_____\___/ \__,_|\___|\___\___/ \_/
                                    v1.6.3

==> Detecting CI provider
    Travis Detected
==> Preparing upload
==> Processing gcov (disable by -X gcov)
    Executing gcov (find /home/travis/build/peterjc/biopython -type f -name '*.gcno'  -exec gcov -pb  {} +)
==> Collecting reports
Error: No coverage report found

Tip: See an example python repo: https://github.com/codecov/example-python
Support channels:
  Email:   hello@codecov.io
  IRC:     #codecov
  Gitter:  https://gitter.im/codecov/support
  Twitter: @codecov
```

Skimming the code, it looks for files like ``gcov.info`` but there is no beginner friendly information in https://github.com/codecov/example-python/blob/master/README.md about where the coverage information comes from. i.e. You seem to assume that something else is already in place to calculate coverage statistics. That's fine, but please say so and give us links to some recommended tools.

In the case of this example repository, the magic is ``coverage run tests.py`` within the ``.travis.yml`` file, which runs the tests and records coverage information - but there is no mention of this yet in the README file.

**Comment by peterjc** [comment]
I see now that the ``coverage`` script from https://pypi.python.org/pypi/coverage is being installed under TravisCI via:

```
$ pip install codecov
...
Successfully installed codecov-1.6.3 coverage-4.0.3 future-0.15.2 importlib-1.0.3 requests-2.8.1
```

**Comment by stevepeak** [comment]
> Sorry for the delay here, missed the notification for this issue.

Codecov will install `coverage`, call `coverage xml` and upload the `coverage.xml` file to be processed server side.

Please let me know if you have questions/feedback about this process, I'm happy to help you out. Thank you!

**Comment by peterjc** [comment]
I got it to work, but I think https://github.com/codecov/example-python/blob/master/README.md and/or https://codecov.io/guide also needs to say you must also run the tests via coverage - probably with a link to https://coverage.readthedocs.org/en/coverage-4.0.3/cmd.html#execution to explain how. e.g.

```
script:
 - python your_test_script.py --your_args
```

becomes at a minimum:

```
script:
 - coverage run your_test_script.py --your_args
```

or more likely, something like:

```
script:
 - coverage run --source=your_source_dir your_test_script.py --your_args
```

Currently this key point is hidden in https://github.com/codecov/example-python/blob/master/.travis.yml without even a comment.

**Comment by peterjc** [comment]
That update looks great - thanks!
