### ISSUE TITLE
Toggling line coverage resets missed lines

### ISSUE THREAD

**Issue by dwahlqvist** [codecov/example-python#17]
Not sure if this is the best place for a general bug report so please move it if needed.

**Steps to reproduce**
1. Navigate to https://codecov.io/gh/codecov/example-python/src/ef8c461aa9f2d7b7a93270328a33da5c7cb366b1/awesome/__init__.py (see screenshot 1) 
2. Set "Toggle Missed" to off - coverage meter changes from 75% to 100%
3. Set "Toggle Missed" to on again - coverage meter stays at 100% (see screenshot 2)

**Expected**
Coverage meter should revert back to 75% after toggling to on

Screenshot 1
<img width="1680" alt="screenshot 2016-07-13 00 39 26" src="https://cloud.githubusercontent.com/assets/5465298/16786136/d777884c-4892-11e6-82d4-f6eef3d83699.png">

Screenshot 2
<img width="1680" alt="screenshot 2016-07-13 00 39 44" src="https://cloud.githubusercontent.com/assets/5465298/16786135/d7732324-4892-11e6-9aec-2eed205cd4d1.png">

**Comment by stevepeak** [comment]
Thank you for pointing this out! I'll fix promptly

**Comment by stevepeak** [comment]
Fixed up 👍

**Comment by dwahlqvist** [comment]
Wow that was quick, awesome!

On Wed, Jul 13, 2016 at 12:17 PM, Steve Peak <notifications@github.com>
wrote:

> Fixed up 👍
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/codecov/example-python/issues/17#issuecomment-232315533>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFNk0kPj8E7Eon4lZDlnDuFxHXBjo7yLks5qVLtXgaJpZM4JK6KP>
> .
>



-- 
Daniel Wahlqvist
+46-704-414270
