### ISSUE TITLE
Add example markdown badge to README

### ISSUE THREAD

**Issue by treyhunner** [codecov/example-python#3]
Just an idea.

You might also want to use a README.rst file though because that seems more common in the Python world due to Sphinx.

**Comment by tobyqin** [comment]
when you import github project to codecov it will generate the badge code for you in there.

**Comment by stevepeak** [comment]
I'm happy to change the readme to an `rst` file.

Badges are found at `https://codecov.io/gh/owner/repo/settings/badge`

Thanks

**Comment by stevepeak** [comment]
I welcome a pull to change `md` to `rst`. I'm not as familiar with rst...

**Comment by gundalow** [comment]
I can do this
Also I'll include the changes from the three open Pull requests (as they are all updates to `README.md`)

**Comment by gundalow** [comment]
Resolved by: https://github.com/codecov/example-python/pull/24

@brifordwylie I don't have any private repos/tokens Do you know this is done?

Feel free to add a comment on the new RST PR https://github.com/codecov/example-python/pull/24
