### ISSUE TITLE
Explain 'repo token'.

### ISSUE THREAD

**Issue by pydanny** [codecov/example-python#4]
Is this a:
1. OAuth token?
2. Personal API Access token?
3. A CI service repo token?
4. Something else entirely?

**Comment by stevepeak** [comment]
The repo token is a secret UUID token that is assigned to a repository. It is required to upload reports to Codecov in all cases, except the following CI providers when the project is open source: Travis, Circle, and AppVeyor.

The repo token is (3) from your list above.

Thank you!

**Comment by colbycheeze** [comment]
I've been searching over an hour through the docs, google, github, and circleci and I am totally lost. Where the crap do you get this magical "CI service repo token??"

**Comment by stevepeak** [comment]
@colbycheeze the upload token is found in your project settings in Codecov. Sorry for not making this more apparent.

`https://codecov.io/gh/<owner>/<repo>/settings`

**Comment by pydanny** [comment]
@stevepeak isn't going to say anything, but as I'm just a customer too (who maintains a lot of open source projects) I will say something:

While @stevepeak could possibly document things better, and I can understand your frustration, tossing in the word "crap" is uncalled for.

**Comment by colbycheeze** [comment]
@pydanny didn't mean anything by the wording. Just writing in frustration. Edited in case others google and land here also. Thx for help :)

**Comment by pydanny** [comment]
I thought as much. No worries :-)

I'm a huge fan of codecov. Best commercial service of its kind. Glad your aboard. :-)

**Comment by colbycheeze** [comment]
Yea agreed, it's good stuff. I just never set it up on a private repo until now haha.

**Comment by stevepeak** [comment]
Thank you @pydanny for your kind words 👍 😄 Working hard to on Codecov every day!

@colbycheeze I hope you find Codecov to be a positive experience as many other have. If I may add: 

- The token is found on the welcome page of the repository (when first setting it up).
- The token is distinguished in the first settings page.
- I recognize that there are missing documentaion on "where to find this magical token" at http://docs.codecov.io/ which I will add now. Thanks to both @pydanny and @colbycheeze for pointing out the lacking of such.

Enjoy my friends 😄 and always know I'm here at your service and for the development community I live-sleep-and-love.

**Comment by stevepeak** [comment]
Here we go 👍  http://docs.codecov.io/docs/frequently-asked-questions#section-where-is-the-repository-upload-token-found-
